### ISSUE TITLE
Highlighting cheapest product.

### ISSUE THREAD

**Issue by MeryHarikaG** [MeryHarikaG/slash-phase5#20]
Cheapest product must be highlighted for the users to easily identify it.
It must be highlighted at the top of all the displayed products which are searched for.
The cheapest product must be highlighted and displayed even after user searches in a price range.

**Comment by tbattul** [comment]
This will help the users pick the cheapest product even after using the filters. It is better to keep it separate and highlighted at the top of the products list displayed. This feature is very useful.
