### ISSUE TITLE
Implement Login Check Before Accessing Wishlist Features

### ISSUE THREAD

**Issue by kothasrilakshmi** [MeryHarikaG/slash-phase5#37]
**Title:** Implement Login Check Before Accessing Wishlist Features

**Description:**

**Issue Overview**
Currently, our application does not validate the user's login status before allowing access to the wishlist features. This oversight can lead to unauthorized access to wishlist functionalities, such as viewing and modifying wishlist items.

<img width="250" height="250" alt="image" src="https://github.com/MeryHarikaG/slash-phase5/assets/145411045/dca5c43b-ef85-4972-a277-ebca642557b7">

**Expected Behavior**
The application should restrict access to the wishlist features, ensuring that only authenticated users can view and interact with their wishlist. Users who are not logged in should be prompted to log in before they can access any wishlist-related functionality.

**Steps to Reproduce**
Navigate to the wishlist page without logging in.
Attempt to view or modify the wishlist items.

**Current Behavior**
The application does not check if the user is logged in.
Unauthenticated users can attempt to access wishlist functionalities.

**Proposed Solution**
Implement a check at the beginning of the render_wishlist function in wishlist.py. This check should verify if the user is authenticated (st.session_state.token is set). If the user is not logged in, the application should display a warning message ("Login first to add item into wishlist.") and prevent further execution of the wishlist logic.

**Additional Context**
This change is crucial for maintaining the integrity and security of user data, especially in features that involve user-specific data like wishlists.

**Comment by tbattul** [comment]
https://github.com/MeryHarikaG/slash-phase5/commit/897317b32017b4624482f1494a239313839ff8f0

**Comment by kothasrilakshmi** [comment]
[lakshmi-dev4](https://github.com/MeryHarikaG/slash-phase5/tree/lakshmi-dev4)
Added additional checks before adding items into wishlist.
